services:
  db:
    image: postgres:16-alpine
    container_name: qe_mini_tasks_db
    environment:
      POSTGRES_USER: qe
      POSTGRES_PASSWORD: qe_pass
      POSTGRES_DB: qe_mini_tasks
    ports:
      - "5433:5432"
    volumes:
      - qe_mini_tasks_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qe -d qe_mini_tasks"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  qe_mini_tasks_pg:
